#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Dylan Barlowe Abel

# Short bio or description (displayed in the header)
description: Accountant 

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://dylanbabel.tk/blog/images/logo.svg

#
# Flags below are optional
#
safe: false
lsi: false
pygments: true

relative_source: ../EXAMPLE/
destination: ../EXAMPLE/

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/dylanbabel/blog.git
# username defaults to ENV['dylanbabel'] used by Travis
# repo defaults to dylanbabel.github.io
# Branch defaults to "master" for dylanbabel.github.io
# or "master" otherwise
username: dylanbabel
repo: blog
branch: master

permalink: pretty

paginate: 10
paginate_path: "blog/page:num"

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github:dylanbabel
  instagram:dylanbabel
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter:
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://dylanbabel.tk

# If you're hosting your site at a Project repository on GitHub pages
# (https://github.com/dylanbabel/blog)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "/blog"

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

remote_theme:Ghost's Casper/Jasper2
# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
